

seq1 = '1−2−4−3−1−2−4−3−1−2−4−3−1−2−4−3−1−2−4−3−1−2−4−3−1−2−4−3−1−2−4−3−1−2−4−3−1−2−4−3−1−2−4−3−1−2−4−3'
seq1a = []
seq1b = []

for a in seq1:
    if a != '−':
        seq1a.append(a)
    else:
        pass

for b in seq1a:
    if b == '1':
        seq1b.append('A')
    elif b == '2':
        seq1b.append('B')
    elif b == '3':
        seq1b.append('C')
    else:
        seq1b.append('D')

seq1f = ''.join(seq1b)
print(seq1f)


seq1 = 'DBCBABABDACBADACACBDACACADBDCDBDACADBCBDADBCDCBC'  # G = .25
seq2 = 'ABCACABABACDCDABDBDBDCABDCDBDCDCABCDBACDBACACDBA'  # G = .40
seq3 = 'BADCDCBDABCBABADCDCBCBCBACBADADADCDABADADCBCBCDA'  # G = .44
seq4 = 'DBCDBACACACACDBDBDBACACACDBCDBACACDABABDBDBACDBD'  # G = .55
seq5 = 'DCDCDCBADCBADCBADCBADCBACBADCBACBABADCBABADCDBAD'  # G = .68
seq6 = 'CBCBDACBDADACBCBCBDACBDACBCBDACBDADACBDADADADACB'  # G = .76
seq7 = 'BCADADADBCADBCADBCADBCADBCBCBCBCADADBCADBCADBCAD'  # G = .79
seq8 = 'BCDABCDABCBCDABCDABCDABCDABCDADABCDABCDABCDABCDA'  # G = .89
seq9 = 'BACDBACDBACDBACDBACDBACDBACDBACDBACDBACDBACDBACD'  # G = 1.0
seq10 = 'ABDCABDCABDCABDCABDCABDCABDCABDCABDCABDCABDCABDC'  # G = 1.0
seq11 = 'DCBADCBADCBADCBADCBADCBADCBADCBADCBADCBADCBADCBA'  # G = 1.0

